### ISSUE TITLE
Backend, Frontend branch를 main branch로 통합하고자 함

### ISSUE THREAD

**Issue by Sion99** [seokiis/KNU-Project1#5]
프론트는 프론트 따로, 백엔드는 백엔드 따로 브랜치가 관리되고 있는 부분이 한눈에 보기에 어렵고, 관리하기도 불편합니다.
이에 브랜치를 main으로 통합을 하면서 각 수정사항이 발생할 때마다 임시 브랜치를 만들고 통합하는 식으로 진행하려고 합니다.

**Comment by Sion99** [comment]
backend -> main으로 merge 완료.

**Comment by yerim10044001** [comment]
main에서 백엔드만을 수정해서 통합하고자 할 때, 의도치 않게 프론트엔드나 다른 파일이 손상될 수 있으므로 
backend 브랜치는 따로 만들어 두고 backend 브랜치에 다른 브랜치를 만들어 수정 후 통합하여 오류가 없는 것이 확인되면 backend 브랜치를 메인 브랜치와 통합하는 것이 좋겠습니다.

**Comment by Sion99** [comment]
11/18 기준 back, front merge 완료
