### ISSUE TITLE
[Backend] 11/17 수정해야 할 목록

### ISSUE THREAD

**Issue by Sion99** [seokiis/KNU-Project1#6]
- 파일 저장폴더 목록 수정 (UPLOAD_FOLDER, PARAM_FOLDER, PLOT_FOLDER)
- download.py 수정
- pyplot.py 삭제
- upload.py 수정
- execute.py 수정

**Comment by yerim10044001** [comment]
파일 저장폴더 이름: UPLOAD_FOLDER
파일 저장 형식: id_filename

파라미터 저장폴더 이름: PARAM_FOLDER
파라미터 저장형식: id_parameter.json

plot html 저장폴더 이름: PLOT_FOLDER
plot html 저장형식: id_plot.html
--------------------------------------------------
upload.py
파라미터(json파일로 저장됨) 파일 저장 시
저장경로 폴더 생성하기(폴더이름 통일하기)

test.py -> 삭제해도 되는 파일

pyplot.py -> 삭제해도 되는 파일

makeplot.py
plot image 저장  파일 이름 변경(id_plot.html으로)
plot image 저장 경로 수정(PLOT_FOLDER)

execute.py
쿠버네티스 연동 후 해야할 일: 
id_parameter.json 파일을 쿠버네티스 yaml파일로 만들어서 HPT 수행 후 결과 받은걸 바탕으로 makeplot 수행

download.py -> 수정필요

**Comment by Sion99** [comment]
- UPLOAD_FOLDER -> uploads 라는 폴더를 생성했습니다.
- PARAM_FOLDER -> parameter 라는 폴더를 생성했습니다.
- PLOT_FOLDER -> plot 이라는 폴더를 생성했습니다. 
- __init__.py -> uploads, parameter, plot 이라는 폴더가 없으면 자동으로 생성하도록 수정했습니다.
- download.py -> download/uploads/파일이름, download/param/파일이름, download/plot/파일이름 주소를 생성하고 각 폴더의 파일을 읽을 수 있게 수정했습니다.

**Comment by Sion99** [comment]
- upload 파일 저장 형식 : id_파일이름
- parameter 파일 저장 형식 : id_parameter.json
- plot 파일 저장 형식 : id_plot.html
- 파일 저장 형식 및 주소 고정하였습니다. 추가적인 수정 없을 예정.
