### ISSUE TITLE
[Doc] 회의록 wiki에 작성

### ISSUE THREAD

**Issue by yerim10044001** [seokiis/KNU-Project1#9]
main branch에 업로드 해두었던 회의록 파일 중 일부가 사라져서 
Wiki에 있는 양식을 바탕으로 작성했던 회의록을 옮겨주시길 바랍니다.
(이전에 작성했던 회의록은 back branch 회의록 폴더에 있습니다.)

**Comment by Sion99** [comment]
PDF 파일로 된 회의록은 전부 올렸습니다. 나머지도 마저 옮겨주시기 바랍니다.

**Comment by yerim10044001** [comment]
- [ ] 220908
- [ ] 220912
- [ ] 220913
- [ ] 220926
- [ ] 220929
- [ ] 221101
- [ ] 221109

**Comment by yerim10044001** [comment]
회의록 위키에 모두 업로드 완료했습니다:)
